[versions]
androidx-activity = "1.9.0"
androidx-junit = "1.1.5"
androidx-appcompat = "1.6.1"
androidx-constraintlayout = "2.1.4"
androidx-datastore = "1.1.1"
androidx-core-splashscreen = "1.0.1"
androidx-browser = "1.8.0"
androidx-core = "1.13.1"
androidx-espresso = "3.5.1"
androidx-legacy-support-v4 = "1.0.0"

androidx-fragment = "1.7.0"
androidx-lifecycle = "2.7.0"
androidx-palette = "1.0.0"
androidx-recyclerview = "1.3.2"
androidx-preference = "1.2.1"
androidx-room = "2.6.1"
androidx-media3 = "1.3.1"
androidx-transition = "1.5.0"
androidx-window = "1.2.0"
androidx-work = "2.9.0"
androidx-navigation = "2.7.7"

androidx-compose = "1.6.7"
androidx-compose-material3 = "1.2.1"
androidx-compose-compiler = "1.5.10"
androidx-constraintlayout-compose = "1.0.1"

google-accompanist = "0.34.0"

material = "1.11.0"
desugar_jdk_libs = "2.0.4"
junit = "4.13.2"

oboe = "1.8.1"
fiesta = "0.2.0"

[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-transition-ktx = { module = "androidx.transition:transition-ktx", version.ref = "androidx-transition" }
androidx-legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "androidx-legacy-support-v4" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-window = { module = "androidx.window:window", version.ref = "androidx-window" }

androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata-core-ktx = { module = "androidx.lifecycle:lifecycle-livedata-core-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }

androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "androidx-preference" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-guava = { module = "androidx.room:room-guava", version.ref = "androidx-room" }

androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "androidx-media3" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "androidx-media3" }

androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }

androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }

androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "androidx-palette" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "androidx-compose"}
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "androidx-compose"}
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "androidx-compose"}
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidx-compose-material3"}
androidx-compose-material3-window = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "androidx-compose-material3"}

androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name ="constraintlayout-compose", version.ref = "androidx-constraintlayout-compose" }

androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "androidx-compose"}
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "androidx-compose"}
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "androidx-compose"}

androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }

google-accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "google-accompanist" }

coil-compose = "io.coil-kt:coil-compose:2.5.0"
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
fiesta-checker = { module = "space.lingu.fiesta:fiesta-checker", version.ref = "fiesta" }
fiesta-annotations = { module = "space.lingu.fiesta:fiesta-annotations", version.ref = "fiesta" }
junit = { module = "junit:junit", version.ref = "junit" }
material = { module = "com.google.android.material:material", version.ref = "material" }
oboe = { module = "com.google.oboe:oboe", version.ref = "oboe" }

[bundles]
androidx-core = [
    "androidx-core-ktx",
    "androidx-core-splashscreen",
    "androidx-window"
]

androidx-appcompat = [
    "androidx-appcompat",
    "androidx-activity-ktx",
    "androidx-fragment-ktx",
    "androidx-transition-ktx",
    "androidx-constraintlayout",
    "androidx-recyclerview",
    "androidx-legacy-support-v4"
]

androidx-lifecycle = [
    "androidx-lifecycle-livedata-ktx",
    "androidx-lifecycle-livedata-core-ktx",
    "androidx-lifecycle-runtime-ktx",
    "androidx-lifecycle-service",
    "androidx-lifecycle-viewmodel-ktx",
    "androidx-lifecycle-viewmodel-savedstate",
    "androidx-lifecycle-viewmodel-compose"
]

androidx-room = [
    "androidx-room-runtime",
    "androidx-room-ktx",
    "androidx-room-guava"
]

androidx-navigation = [
    "androidx-navigation-ui-ktx",
    "androidx-navigation-fragment-ktx",
    "androidx-navigation-compose"
]

androidx-media3 = [
    "androidx-media3-session",
    "androidx-media3-exoplayer"
]

androidx-work = [
    "androidx-work-runtime-ktx"
]

androidx-compose = [
    "androidx-activity-compose",
    "androidx-compose-foundation",
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-material3",
    "androidx-compose-material3-window",
    "androidx-constraintlayout-compose"
]

accompanist = [
    "google-accompanist-permissions"
]

androidx-test = [
    "androidx-junit",
    "androidx-espresso-core"
]

[plugins]

